version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
    groups:
      python:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-loader"
      npm:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directories:
      - compose/local/django/
      - compose/local/docs/
      - compose/production/django/
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    groups:
      docker-python:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - compose/local/node/
      - compose/production/postgres/
      - compose/production/traefik/
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20

  - package-ecosystem: helm
    directory: charts/galactus/
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
    groups:
      helm:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/Los_Angeles
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
    groups:
      pre-commit:
        patterns:
          - "*"
