---
version: "3"
services:
  galactus:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        GROUP_ID: "${GROUP_ID:-1000}"
    image: galactus/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      USER_ID: "${USER_ID:-1000}"
      USER: "${USER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
    networks:
      - galactus
    depends_on:
      - pgsql
      - redis
      - meilisearch
  pgsql:
    image: "postgres:13"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "galactus-pgsql:/var/lib/postgresql/data"
    networks:
      - galactus
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "galactus-redis:/data"
    networks:
      - galactus
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - "galactus-meilisearch:/data.ms"
    networks:
      - galactus
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
networks:
  galactus:
    driver: bridge
volumes:
  galactus-pgsql:
    driver: local
  galactus-redis:
    driver: local
  galactus-meilisearch:
    driver: local
