---
version: "3"
services:
  laravel.test:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: galactus/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      WWWGROUP: "${WWWGROUP}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
    networks:
      - galactus
    depends_on:
      - pgsql
      - redis
      - meilisearch
      - selenium
  pgsql:
    image: "postgres:14.2"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "galactus-pgsql:/var/lib/postgresql/data"
    networks:
      - galactus
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
  redis:
    image: "redis:6.2.6-alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "galactus-redis:/data"
    networks:
      - galactus
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  meilisearch:
    image: "getmeili/meilisearch:v0.25.2"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - "galactus-meilisearch:/data.ms"
    networks:
      - galactus
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
  mailhog:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - galactus
  selenium:
    image: "selenium/standalone-chrome"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - galactus
networks:
  galactus:
    driver: bridge
volumes:
  galactus-pgsql:
    driver: local
  galactus-redis:
    driver: local
  galactus-meilisearch:
    driver: local
