apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "galactus.fullname" . }}-web
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.web.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "galactus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "galactus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.externalSecrets.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/external-secret.yaml") . | sha256sum }}
        {{- else }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "galactus.serviceAccountName" . }}
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{ .Values.web.args | toJson }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          envFrom:
            {{- include "galactus.envFrom" . | nindent 12 }}
          {{- with .Values.web.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- if .Values.gcp.credentialsSecret }}
          volumeMounts:
            {{- include "galactus.gcpVolumeMount" . | nindent 12 }}
          {{- end }}
      {{- if .Values.gcp.credentialsSecret }}
      volumes:
        {{- include "galactus.gcpVolume" . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
