apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "galactus.fullname" . }}-celery-worker
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  {{- if not .Values.keda.enabled }}
  replicas: {{ .Values.celeryWorker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "galactus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "galactus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.externalSecrets.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/external-secret.yaml") . | sha256sum }}
        {{- else }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "galactus.serviceAccountName" . }}
      containers:
        - name: celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{ .Values.celeryWorker.args | toJson }}
          envFrom:
            {{- include "galactus.envFrom" . | nindent 12 }}
          {{- with .Values.celeryWorker.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.celeryWorker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
          {{- if .Values.gcp.credentialsSecret }}
          volumeMounts:
            {{- include "galactus.gcpVolumeMount" . | nindent 12 }}
          {{- end }}
      {{- if .Values.gcp.credentialsSecret }}
      volumes:
        {{- include "galactus.gcpVolume" . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
