{{- if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "galactus.fullname" . }}-flower
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  replicas: {{ .Values.flower.replicas }}
  selector:
    matchLabels:
      {{- include "galactus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: flower
  template:
    metadata:
      labels:
        {{- include "galactus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: flower
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "galactus.serviceAccountName" . }}
      containers:
        - name: flower
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{ .Values.flower.args | toJson }}
          ports:
            - name: flower
              containerPort: {{ .Values.flower.port }}
              protocol: TCP
          envFrom:
            {{- include "galactus.envFrom" . | nindent 12 }}
          {{- with .Values.flower.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: flower
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: flower
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.flower.resources | nindent 12 }}
          {{- if .Values.gcp.credentialsSecret }}
          volumeMounts:
            {{- include "galactus.gcpVolumeMount" . | nindent 12 }}
          {{- end }}
      {{- if .Values.gcp.credentialsSecret }}
      volumes:
        {{- include "galactus.gcpVolume" . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
