{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "galactus.fullname" . }}
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.store.name }}
    kind: {{ .Values.externalSecrets.store.kind }}
  target:
    name: {{ include "galactus.fullname" . }}
    creationPolicy: Owner
  data:
    {{- range $key, $remoteRef := .Values.externalSecrets.secretMapping }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $remoteRef }}
    {{- end }}
{{- end }}
