{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "galactus.fullname" . }}-web
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  podSelector:
    matchLabels:
      {{- include "galactus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - port: {{ .Values.web.port }}
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "galactus.fullname" . }}-celery
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "galactus.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to: []
      ports:
        - port: 5432
          protocol: TCP
        - port: 6379
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
