{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "galactus.fullname" . }}-web
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "galactus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
