{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "galactus.fullname" . }}
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secret.djangoSecretKey | quote }}
  POSTGRES_USER: {{ include "galactus.postgresUser" . | quote }}
  POSTGRES_PASSWORD: {{ include "galactus.postgresPassword" . | quote }}
  SENDGRID_API_KEY: {{ .Values.secret.sendgridApiKey | quote }}
  SENTRY_DSN: {{ .Values.secret.sentryDsn | quote }}
  DJANGO_ADMIN_URL: {{ .Values.secret.djangoAdminUrl | quote }}
  CELERY_FLOWER_USER: {{ .Values.secret.celeryFlowerUser | quote }}
  CELERY_FLOWER_PASSWORD: {{ .Values.secret.celeryFlowerPassword | quote }}
  {{- if .Values.secret.googleApplicationCredentials }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.secret.googleApplicationCredentials | quote }}
  {{- end }}
{{- end }}
