apiVersion: v1
kind: Service
metadata:
  name: {{ include "galactus.fullname" . }}-web
  labels:
    {{- include "galactus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "galactus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
