#!/usr/bin/env bash

if [ ! -z "$USER_ID" ]; then
  usermod -u $USER_ID $USER
fi

if [ ! -d /.composer ]; then
  mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
  exec gosu $USER_ID "$@"
else
  /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
