apiVersion: v2
name: galactus
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">= 1.20.0-0"
icon: https://raw.githubusercontent.com/acchiao/galactus/main/charts/galactus/chart-icon.png
description: The All-Knowing User Service Provider Aggregator.
type: application
keywords:
  - galactus
home: https://github.com/acchiao/galactus
sources:
  - https://github.com/acchiao/galactus
dependencies:
  - name: postgresql
    version: ^11.1.3
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
    condition: postgresql.enabled
  - name: redis
    version: ^16.4.4
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
  - name: meilisearch
    version: ^0.1.26
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    alias: meilisearch
    condition: meilisearch.enabled
