name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [main]
    paths-ignore: [docs/**]
  pull_request:
    branches: [main]
    paths-ignore: [docs/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - uses: pre-commit/action@v3.0.1

  prettier:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run format:check

  super-linter:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: super-linter/super-linter@v8.6.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: charts/.*

  pytest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v4
      - uses: docker/bake-action@v7
        with:
          push: false
          load: true
          files: docker-compose.local.yml
          targets: django
          set: |
            django.cache-from=type=gha,scope=django-cached-tests
            django.cache-to=type=gha,scope=django-cached-tests,mode=max
            postgres.cache-from=type=gha,scope=postgres-cached-tests
            postgres.cache-to=type=gha,scope=postgres-cached-tests,mode=max
      - uses: docker/bake-action@v7
        with:
          push: false
          load: true
          files: docker-compose.docs.yml
          set: |
            docs.cache-from=type=gha,scope=cached-docs
            docs.cache-to=type=gha,scope=cached-docs,mode=max
      - run: docker compose -f docker-compose.local.yml run --rm django python manage.py makemigrations --check
      - run: docker compose -f docker-compose.local.yml run --rm django python manage.py migrate
      - run: docker compose -f docker-compose.local.yml run django pytest
      - run: docker compose -f docker-compose.local.yml down
